- docs/Get-vRAReservation.md
Fixed an issue with a broken document for readthedocs
> Fixed broken doc

- PowervRA/Functions/Public/Export-vRAContentPackage.psm1
- PowervRA/Functions/Public/Invoke-vRARestMethod.psm1
- PowervRA/Functions/Public/Test-vRAContentPackage.psm1
- PowervRA/PowervRA.psd1
- tests/Test007-ContentPackage.Tests.ps1
- tests/Variables.json
Added Test-vRAContentpackage
Used Test-vRAContentpackage in Import-vRAContentPackage for issue #57 
Resolved issue #50 
Resolved issue #58
> Feature validatecontentpackages

- PowervRA/Functions/Public/New-vRABusinessGroup.psm1
> fixes issue #55

- PowervRA/Functions/Public/Set-vRAReservationNetwork.psm1
> Bugfix set vrareservationnetwork

- PowervRA/Functions/Private/New-DynamicParam.ps1
- PowervRA/Functions/Public/properties-service/Get-vRAPropertyDefinition.ps1
- PowervRA/Functions/Public/properties-service/New-vRAPropertyDefinition.ps1
- PowervRA/Functions/Public/properties-service/Remove-vRAPropertyDefinition.ps1
> Added properties service

- PowervRA/Functions/Public/Invoke-vRARestMethod.ps1
Adds Write-Debug -Message $Body to Invoke-vRARestMethod.
Enables users to see the payloads sent when using New/Set/Import functions.
#78
> Adds Write-Debug when Body is passed

- PowervRA/Functions/Public/reservation-service/Remove-vRAReservationNetwork.ps1
- tests/Test008-Reservation.Tests.ps1
Implements Remove-vRAReservationNetwork
> Initial commit for Remove-vRAReservationNetwork

- PowervRA/Functions/Public/identity/Get-vRAUserPrincipalGroupMembership.ps1
- tests/Test009-Principal.Tests.ps1
Implements Get-vRAUserPrincipalGroupMembership
> Initial commit for Get-vRAUserPrincipalGroupMembership

- PowervRA/Functions/Public/o11n-gateway-service/Invoke-vRADataCollection.ps1
- tests/Test013-O11n-Gateway-Service.Tests.ps1
Implements Invoke-vRADataCollection * tests
> Initial commit for Invoke-vRADataCollection

- PowervRA/Functions/Public/iaas-proxy-provider/Get-vRASourceMachine.ps1
- tests/Test010-IaaS-Proxy-Provider.Tests.ps1
* Implements Get-vRASourceMachine & Tests
> Initial commit for Get-vRASourceMachine

- PowervRA/Functions/Private/xRequires.ps1
> Updates to use Write-Error and break, also adds FunctionRequires Alias

- PowervRA/Functions/Private/NewDynamicParam.ps1
- PowervRA/Functions/Public/catalog-service/Get-vRAResourceActionRequestTemplate.ps1
- PowervRA/Functions/Public/iaas-proxy-provider/Get-vRASourceMachine.ps1
- PowervRA/Functions/Public/properties-service/New-vRAPropertyDefinition.ps1
- PowervRA/Functions/Public/reservation-service/Set-vRAReservationNetwork.ps1
- build.psake.ps1
- Moves any internal functions inside the parent functions
- Changes internal function names to int*
- Adds extra validation in to build script to ensure that internal functions are not exported
> Bugfix internal functions

- build.psake.ps1
The CreateArtifact build task will now compile all of the functions in to a single psm1
> Feature single psm1

- PowervRA/Functions/Public/Invoke-vRARestMethod.ps1
- PowervRA/Functions/Public/catalog-service/Request-vRAResourceAction.ps1
Replace PR #144  #146 
Mostly reuse your code for :
_ Invoke-WebRequest from feature-invoke-vrarestmethod-improvements
_ Wait parameter from Request-vRACatalogItem.ps1
> Adds -Wait parameter & fix missing request object return

- PowervRA/Functions/Public/reservation-service/Get-vRAReservationPolicy.ps1
- PowervRA/Functions/Public/reservation-service/Get-vRAStorageReservationPolicy.ps1
Same fix also for Get-vRAStorageReservationPolicy
> To fix issue #151 with Limits not implemented

- PowervRA/Functions/Public/reservation-service/Get-vRAReservationComputeResource.ps1
- PowervRA/Functions/Public/reservation-service/Get-vRAReservationComputeResourceMemory.ps1
- PowervRA/Functions/Public/reservation-service/Get-vRAReservationComputeResourceNetwork.ps1
- PowervRA/Functions/Public/reservation-service/Get-vRAReservationComputeResourceResourcePool.ps1
- PowervRA/Functions/Public/reservation-service/Get-vRAReservationComputeResourceStorage.ps1
- PowervRA/Functions/Public/reservation-service/Get-vRAReservationType.ps1
- PowervRA/Functions/Public/reservation-service/New-vRAReservation.ps1
- PowervRA/Functions/Public/reservation-service/New-vRAReservationNetworkDefinition.ps1
- PowervRA/Functions/Public/reservation-service/New-vRAReservationStorageDefinition.ps1
Updates for Resource Type changes in vRA 7.2+ to fix issue #149
> Updates for Resource Type changes in vRA 7.2+

- README.md
- src/Functions/Public/Connect-vRAServer.ps1
- src/Functions/Public/Disconnect-vRAServer.ps1
- src/Functions/Public/Invoke-vRARestMethod.ps1
Support for custom SSL protocols to fix issue #130
> Feature ssl protocol from master

- src/Functions/Public/Connect-vRAServer.ps1
- src/Functions/Public/Disconnect-vRAServer.ps1
- src/Functions/Public/Invoke-vRARestMethod.ps1
Updates to use $IsCoreCLR inbuilt variable
Have tested on both Windows PS and PS Core
To resolve issue #162
> Updates to use $IsCoreCLR inbuilt variable

- src/Functions/Public/identity/Get-vRATenantDirectory.ps1
- tests/Test002-Tenant.Tests.ps1
Added a foreach statement to handle returning multiple directories
> Bugfix Get-vRATenantDirectory multiple directories

- src/Functions/Public/catalog-service/Set-vRAEntitlement.ps1
- src/Functions/Public/identity/Remove-vRABusinessGroup.ps1
- src/Functions/Public/identity/Set-vRAStorageReservationPolicy.ps1
- src/Functions/Public/reservation-service/Set-vRAReservationPolicy.ps1
Changed Set-vRAEntitlement to use Get-vRACatalogItem instead of Get-vRAEntitledCatalogItem to fix issue #180
> Changed Set-vRAEntitlement to use Get-vRACatalogItem

- src/Functions/Public/identity/Get-vRABusinessGroup.ps1
- src/Functions/Public/identity/New-vRABusinessGroup.ps1
Added SharedAccess parameter to New-vRABusinessGroup for issue #183
Updated output of Get-vRABusinessGroup to include SharedAccess
> Added SharedAccess parameter to New-vRABusinessGroup for issue #183

- src/Functions/Public/Connect-vRAServer.ps1
Added section to throw if the username is in the format Domain\Username to solve issue #189
> Added section to throw if the username is in the format Domain\Username

- src/Functions/Public/catalog-service/Request-vRACatalogItem.ps1
- src/Functions/Public/catalog-service/Request-vRAResourceAction.ps1
> Use IsPresent on switch, throw on Reject

- src/Functions/Public/catalog-service/Get-vRAEntitledCatalogItem.ps1
> fix EntitledOrganizations on Standard paramset

- src/Functions/Public/Invoke-vRARestMethod.ps1
Added PATCH method to Invoke-vRARestMethod to resolve issue #244
> Added PATCH method to Invoke-vRARestMethod

- src/Functions/Public/iaas/New-vRAProject.ps1
Added Viewers parameter to New-vRAProject to resolve #242 
Modified unnecessary mandatory parameters
> Added Viewers parameter to New-vRAProject

- src/Functions/Public/iaas/Get-vRAFabricAzureStorageAccount.ps1
Added missing help for Id and Name parameters #247
> Added missing help for Id and Name parameters #247

- azure-pipelines.yml
Added support for PRs to the master branch #249
> Added support for PRs to the master branch #249

- .github/workflows/ps-module.yml
- README.md
- mkdocs.yml
- tools/build.ps1
- tools/build.psake.ps1
Auto builds markdown doc file for each function using platyPS
Added support for mkdocs publishing to GitHub Pages
To resolve #253
> Automate creation and publishing of function documentation

- README.md
Updated Documentation section of Readme
> Updated Documentation section of Readme

- src/Functions/Public/iaas/New-vRAVirtualDisk.ps1
- tools/build.psake.ps1
Updated psake build to search functions for aliases and add them to the manifest. Also sorted the results alphabetically before writing them to the manifest file `($ExportFunctions | Sort-Object)`
Updated `New-vRAVirtualDIsk` to specifically export the alias
To close #260
> Updated build for aliases

- src/Functions/Public/Disconnect-vRAServer.ps1
Replaced references to Global with Script
To close #262
> Replaced references to Global with Script

- .github/workflows/ps-module.yml
Updated Pipeline to run step 'Publish Unit Test Results' in the 'Build module' job
To close #264
> Updated Pipeline to run step 'Publish Unit Test Results' in the 'Build module' job

- README.md
Updated Readme with details of Breaking Changes
> Updated Readme with details of Breaking Changes

- .github/workflows/ps-module.yml
- tools/build.ps1
- tools/build.psake.ps1
Set fixed PowerShell module versions
Also set GitVersion version to previous version 5.6.9 because of this issue: https://github.com/GitTools/GitVersion/issues/2711
> Set fixed PowerShell module versions

- src/Functions/Public/Invoke-vRARestMethod.ps1
VRA pages start at 0 not at 1 and this issue causes missing entries.
> Fix Missing Entries when Paging is used

- .github/workflows/ps-module.yml
This will enable us to merge the pending open PRs for the support/v3 branch
> Added support to CI process for support branches

- src/Functions/Public/catalog-service/Get-vRACatalogPrincipal.ps1
Fixes for issue #272 
Reset $CatalogPrincipal at the begining of loop
> Fix $catalogPrincipal reset

- src/Functions/Public/Connect-vRAServer.ps1
Updated the URI of the auth API endpoint to match the documented URI (for both the user/pass endpoint and the APIToken endpoint).
> Fixes deprecated/removed auth API endpoint - Issue #287
